"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'asn1crypto',
        'bcrypt',
        'cffi',
        'cryptography',
        'Fabric',
        'Flask-SQLAlchemy',
        'idna',
        'itsdangerous',
        'Jinja2',
        'MarkupSafe',
        'paramiko',
        'pyasn1',
        'pycparser',
        'PyNaCl',
        'six',
        'SQLAlchemy',
        'Werkzeug'
    ]
)


